Disable warning C4819. (#326)
Because, when it happens that Visual C++ compiles UTF-8 files without BOM as cp932 encoding on Japanese locale.
Falcor\external\packman\nanovdb\include\nanovdb\NanoVDB.h
Falcor\external\packman\deps\include\FreeImage.h

Error Messages:
Falcor\external\packman\nanovdb\include\nanovdb/NanoVDB.h(1,1): error C2220: 次の警告はエラーとして処理されます
Falcor\external\packman\nanovdb\include\nanovdb/NanoVDB.h(1,1): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。

Falcor\external\packman\deps\include\FreeImage.h(1,1): error C2220: 次の警告はエラーとして処理されます
Falcor\external\packman\deps\include\FreeImage.h(1,1): warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。